import {
  Award,
  Box,
  Brain,
  Building2,
  CheckCircle2,
  ClipboardCheck,
  Factory,
  Flame,
  GitBranch,
  GraduationCap,
  HardHat,
  HeartHandshake,
  HeartPulse,
  MapPin,
  MoveUp,
  PackageOpen,
  ScrollText,
  Settings2,
  ShieldAlert,
  ShieldCheck,
  Stethoscope,
  Truck,
  Users,
  Utensils,
  UtensilsCrossed,
  Volume2,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  Award,
  Box,
  Brain,
  Building2,
  CheckCircle2,
  ClipboardCheck,
  Factory,
  Flame,
  GitBranch,
  GraduationCap,
  HardHat,
  HeartHandshake,
  HeartPulse,
  MapPin,
  MoveUp,
  PackageOpen,
  ScrollText,
  Settings2,
  ShieldAlert,
  ShieldCheck,
  Stethoscope,
  Truck,
  Users,
  Utensils,
  UtensilsCrossed,
  Volume2,
  Wrench,
  Zap,
};

export const iconNames = Object.keys(iconMap).sort();

export function getIcon(name?: string | null): LucideIcon {
  return (name && iconMap[name]) || ShieldCheck;
}
