/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormationsIndexRouteImport } from './routes/formations.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrainingSlugRouteImport } from './routes/training.$slug'
import { Route as FormationsSlugRouteImport } from './routes/formations.$slug'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminSectorsRouteImport } from './routes/admin.sectors'
import { Route as AdminSectionsRouteImport } from './routes/admin.sections'
import { Route as AdminReferencesRouteImport } from './routes/admin.references'
import { Route as AdminNavRouteImport } from './routes/admin.nav'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFormationsRouteImport } from './routes/admin.formations'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsIndexRoute = FormationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormationsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrainingSlugRoute = TrainingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrainingRoute,
} as any)
const FormationsSlugRoute = FormationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FormationsRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectorsRoute = AdminSectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferencesRoute = AdminReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavRoute = AdminNavRouteImport.update({
  id: '/nav',
  path: '/nav',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormationsRoute = AdminFormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/references': typeof ReferencesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRouteWithChildren
  '/admin/formations': typeof AdminFormationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/nav': typeof AdminNavRoute
  '/admin/references': typeof AdminReferencesRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/sectors': typeof AdminSectorsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/formations/$slug': typeof FormationsSlugRoute
  '/training/$slug': typeof TrainingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/formations/': typeof FormationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/references': typeof ReferencesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRouteWithChildren
  '/admin/formations': typeof AdminFormationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/nav': typeof AdminNavRoute
  '/admin/references': typeof AdminReferencesRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/sectors': typeof AdminSectorsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/formations/$slug': typeof FormationsSlugRoute
  '/training/$slug': typeof TrainingSlugRoute
  '/admin': typeof AdminIndexRoute
  '/formations': typeof FormationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/references': typeof ReferencesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRouteWithChildren
  '/admin/formations': typeof AdminFormationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/nav': typeof AdminNavRoute
  '/admin/references': typeof AdminReferencesRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/sectors': typeof AdminSectorsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/formations/$slug': typeof FormationsSlugRoute
  '/training/$slug': typeof TrainingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/formations/': typeof FormationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/consulting'
    | '/contact'
    | '/formations'
    | '/privacy'
    | '/references'
    | '/sitemap.xml'
    | '/terms'
    | '/training'
    | '/admin/formations'
    | '/admin/login'
    | '/admin/nav'
    | '/admin/references'
    | '/admin/sections'
    | '/admin/sectors'
    | '/admin/seo'
    | '/admin/services'
    | '/formations/$slug'
    | '/training/$slug'
    | '/admin/'
    | '/formations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consulting'
    | '/contact'
    | '/privacy'
    | '/references'
    | '/sitemap.xml'
    | '/terms'
    | '/training'
    | '/admin/formations'
    | '/admin/login'
    | '/admin/nav'
    | '/admin/references'
    | '/admin/sections'
    | '/admin/sectors'
    | '/admin/seo'
    | '/admin/services'
    | '/formations/$slug'
    | '/training/$slug'
    | '/admin'
    | '/formations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/consulting'
    | '/contact'
    | '/formations'
    | '/privacy'
    | '/references'
    | '/sitemap.xml'
    | '/terms'
    | '/training'
    | '/admin/formations'
    | '/admin/login'
    | '/admin/nav'
    | '/admin/references'
    | '/admin/sections'
    | '/admin/sectors'
    | '/admin/seo'
    | '/admin/services'
    | '/formations/$slug'
    | '/training/$slug'
    | '/admin/'
    | '/formations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConsultingRoute: typeof ConsultingRoute
  ContactRoute: typeof ContactRoute
  FormationsRoute: typeof FormationsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ReferencesRoute: typeof ReferencesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrainingRoute: typeof TrainingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/': {
      id: '/formations/'
      path: '/'
      fullPath: '/formations/'
      preLoaderRoute: typeof FormationsIndexRouteImport
      parentRoute: typeof FormationsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/training/$slug': {
      id: '/training/$slug'
      path: '/$slug'
      fullPath: '/training/$slug'
      preLoaderRoute: typeof TrainingSlugRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/formations/$slug': {
      id: '/formations/$slug'
      path: '/$slug'
      fullPath: '/formations/$slug'
      preLoaderRoute: typeof FormationsSlugRouteImport
      parentRoute: typeof FormationsRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sectors': {
      id: '/admin/sectors'
      path: '/sectors'
      fullPath: '/admin/sectors'
      preLoaderRoute: typeof AdminSectorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/references': {
      id: '/admin/references'
      path: '/references'
      fullPath: '/admin/references'
      preLoaderRoute: typeof AdminReferencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nav': {
      id: '/admin/nav'
      path: '/nav'
      fullPath: '/admin/nav'
      preLoaderRoute: typeof AdminNavRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/formations': {
      id: '/admin/formations'
      path: '/formations'
      fullPath: '/admin/formations'
      preLoaderRoute: typeof AdminFormationsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFormationsRoute: typeof AdminFormationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNavRoute: typeof AdminNavRoute
  AdminReferencesRoute: typeof AdminReferencesRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminSectorsRoute: typeof AdminSectorsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFormationsRoute: AdminFormationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNavRoute: AdminNavRoute,
  AdminReferencesRoute: AdminReferencesRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminSectorsRoute: AdminSectorsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FormationsRouteChildren {
  FormationsSlugRoute: typeof FormationsSlugRoute
  FormationsIndexRoute: typeof FormationsIndexRoute
}

const FormationsRouteChildren: FormationsRouteChildren = {
  FormationsSlugRoute: FormationsSlugRoute,
  FormationsIndexRoute: FormationsIndexRoute,
}

const FormationsRouteWithChildren = FormationsRoute._addFileChildren(
  FormationsRouteChildren,
)

interface TrainingRouteChildren {
  TrainingSlugRoute: typeof TrainingSlugRoute
}

const TrainingRouteChildren: TrainingRouteChildren = {
  TrainingSlugRoute: TrainingSlugRoute,
}

const TrainingRouteWithChildren = TrainingRoute._addFileChildren(
  TrainingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ConsultingRoute: ConsultingRoute,
  ContactRoute: ContactRoute,
  FormationsRoute: FormationsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ReferencesRoute: ReferencesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrainingRoute: TrainingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
